# Generator

## To create Generator following attributes must be given
1. Number of Jobs
2. Number of Machines
3. Minimum Time required for a amachine to process an operation
4. Maximum Time required for a machine to process an operation
5. Mean Time Between Failures to simulate machine breakdowns
6. Mean Time To Repair to simulate machine breakdowns

In [1]:
from rl4co.envs.scheduling.djssp.generator import DJSSPGenerator

djssp_generator = DJSSPGenerator(
    num_jobs=6 ,
    num_machines= 6 ,
    min_processing_time= 1 ,
    max_processing_time= 200 ,
    mtbf = 17 ,
    mttr = 4
)

C:\Users\soner\anaconda3\envs\env_rl4co\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## _generate()
- INPUT: takes iterable batch_size as an input
- OUTPUT: Tensor dict containing
    - Start operation per Job
    - Last operation per Job
    - Estimated processing times (td["proc_times"])
    - Stochastic/actual processing times (td["actual_proc_times"])
    - pad_mask

In [2]:
td =djssp_generator._generate(batch_size=[6,])

### td["start_op_per_job"]
- `[batch_size, num_jobs]`: first operation of each job

In [3]:
td["start_op_per_job"]

tensor([[ 0,  6, 12, 18, 24, 30],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  6, 12, 18, 24, 30]])

In [4]:
td["start_op_per_job"].shape

torch.Size([6, 6])

- Start Operation of Jobs in batch 0

In [5]:
td["start_op_per_job"][0]

tensor([ 0,  6, 12, 18, 24, 30])

### td["end_op_per_job"]
- [batch_size, num_jobs]: last operation of each job

In [6]:
td["end_op_per_job"]

tensor([[ 5, 11, 17, 23, 29, 35],
        [ 5, 11, 17, 23, 29, 35],
        [ 5, 11, 17, 23, 29, 35],
        [ 5, 11, 17, 23, 29, 35],
        [ 5, 11, 17, 23, 29, 35],
        [ 5, 11, 17, 23, 29, 35]])

In [7]:
td["end_op_per_job"].shape

torch.Size([6, 6])

In [8]:
td["end_op_per_job"][2]

tensor([ 5, 11, 17, 23, 29, 35])

### td["proc_times"]
-`[batch_size, num_machines , total_n_ops]`: estimated processing time of operations on machines

In [9]:
td["proc_times"].shape

torch.Size([6, 6, 36])

In [10]:
td["proc_times"]

tensor([[[  0.,   0., 123.,  ...,  90.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0., 105.,   0.,  ...,   0.,   0.,   0.],
         [164.,   0.,   0.,  ...,   0.,   0., 126.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,  86.,   0.]],

        [[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [ 95.,   0.,   0.,  ...,  19.,   0.,   0.],
         [  0.,  37.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,  74.,  ...,   0., 167.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0., 178.]],

        [[  0.,   0.,   0.,  ...,   0., 130.,   0.],
         [ 10.,   0.,   0.,  ..., 127.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  0.,   0.,  82.,  ...,   0.,   0.,  32.],
         [  0., 148.,   0.,  ...,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,  ...,  88., 

- Estimated Processing time of operations on machines in Batch 0
  - EX: in batch 0; machine 0 can process operation 0 on 7 time units => td["proc_times"][0][machine_no][operation_no]

In [11]:
td["proc_times"][0]

tensor([[  0.,   0., 123.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 142.,
           0.,   0.,   0.,   0.,   0., 163.,   0.,   0.,   0.,   0.,   0.,   5.,
           0.,   0.,   0.,   0.,   0.,  10.,   0.,   0.,   0.,  90.,   0.,   0.],
        [  0.,   0.,   0.,  55.,   0.,   0.,   0.,   0.,   0., 144.,   0.,   0.,
           0.,   0.,   0.,   0., 125.,   0., 100.,   0.,   0.,   0.,   0.,   0.,
          39.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  78.,   0.,   0.,   0.],
        [  0., 105.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  66.,   0.,
           0.,   0., 122.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 164.,   0.,
           0.,   0.,   0.,   0.,  84.,   0.,   0.,  46.,   0.,   0.,   0.,   0.],
        [164.,   0.,   0.,   0.,   0.,   0., 192.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,  55.,   0.,   0.,   0.,   0.,  53.,   0.,   0.,   0.,
           0.,   0.,   0.,  76.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 126.],
        [  0.,   0.,   0

### td["actual_proc_times"]
- `[batch_size, num_machines , total_n_ops]`: actual processing time of operations on machines
- calculated by : `_simulate_actual_processing_times()`

In [12]:
td["actual_proc_times"]

tensor([[[  0.0000,   0.0000, 117.6933,  ...,  86.7888,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [  0.0000, 112.9930,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [182.3142,   0.0000,   0.0000,  ...,   0.0000,   0.0000, 145.8596],
         [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,  ...,   0.0000,  80.6574,   0.0000]],

        [[  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [ 91.2300,   0.0000,   0.0000,  ...,  21.4536,   0.0000,   0.0000],
         [  0.0000,  36.9711,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,  85.3339,  ...,   0.0000, 180.0727,   0.0000],
         [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000, 177.9814]],

        [[  0.0000,   0.0000,   0.0000,  ...,   0.0000, 118.8961,   0.00

- Shape

In [13]:
td["actual_proc_times"].shape

torch.Size([6, 6, 36])

- Example : Actual processing time of operation 6 on machine 3 in batch 0

In [14]:
td["actual_proc_times"][0][3][6].item()

184.41258239746094

### td["machine_breakdowns"]
- Index: Represents machine ID's
- TIME: The timestamp when the breakdown occurred
- DURATION: The duration of the breakdown

In [15]:
td["machine_breakdowns"]

array([{0: [{'TIME': 3.000108480453491, 'DURATION': 10.950005531311035}, {'TIME': 35.32599139213562, 'DURATION': 1.3882921934127808}, {'TIME': 62.19732415676117, 'DURATION': 10.096503257751465}], 1: [{'TIME': 29.66557502746582, 'DURATION': 1.5291308164596558}, {'TIME': 40.57259452342987, 'DURATION': 1.0042990446090698}, {'TIME': 80.03481256961823, 'DURATION': 2.711613416671753}], 2: [{'TIME': 12.460824966430664, 'DURATION': 0.07522933185100555}, {'TIME': 53.31210486590862, 'DURATION': 1.205381989479065}, {'TIME': 70.82343074679375, 'DURATION': 0.6587216854095459}], 3: [{'TIME': 6.723081111907959, 'DURATION': 2.6919376850128174}, {'TIME': 38.85593867301941, 'DURATION': 0.6645970344543457}, {'TIME': 57.83890724182129, 'DURATION': 3.2587645053863525}], 4: [{'TIME': 15.107711791992188, 'DURATION': 8.416229248046875}, {'TIME': 26.383179187774658, 'DURATION': 3.2661590576171875}, {'TIME': 89.99576234817505, 'DURATION': 1.8107106685638428}], 5: [{'TIME': 1.7039726972579956, 'DURATION': 0.3539

- Type = numpy.ndarray
- Size = number of batches 

In [16]:
print(type(td["machine_breakdowns"]))
print(len(td["machine_breakdowns"]))

<class 'numpy.ndarray'>
6


- Breakdown of the machine 4 in batch 0

In [17]:
td["machine_breakdowns"][0][4]

[{'TIME': 15.107711791992188, 'DURATION': 8.416229248046875},
 {'TIME': 26.383179187774658, 'DURATION': 3.2661590576171875},
 {'TIME': 89.99576234817505, 'DURATION': 1.8107106685638428}]

- Extracting Breakdown occurence time and breakdown duration

In [18]:
# breakdowns of the machine 5 in batch 3
b5 = td["machine_breakdowns"][3][5]
print(f"BREAKDOWNS OF MACHINE 5 IN BATCH 3{b5}")

print("--------------------------------------------")

# first breakdown occurence time of machine 5 in batch 3
first_b5 = td["machine_breakdowns"][3][5][0]["TIME"]
print(f"BREAKDOWN OCCURENCE : {first_b5}")

print("--------------------------------------------")

# first breakdown duration of machine 5 in batch 3
first_b5_duration = td["machine_breakdowns"][3][5][0]["DURATION"]
print(f"BREAKDOWN DURATION : {first_b5_duration}")

BREAKDOWNS OF MACHINE 5 IN BATCH 3[{'TIME': 32.70050048828125, 'DURATION': 2.011552572250366}, {'TIME': 46.81283640861511, 'DURATION': 4.536108016967773}, {'TIME': 113.29264879226685, 'DURATION': 0.011085120029747486}]
--------------------------------------------
BREAKDOWN OCCURENCE : 32.70050048828125
--------------------------------------------
BREAKDOWN DURATION : 2.011552572250366


#### documentation of `._simulate_machine_breakdowns_with_mtbf_mttr()` method 

In [19]:
import numpy as np

machine_breakdowns = djssp_generator._simulate_machine_breakdowns_with_mtbf_mttr(bs = [4,] , 
                                                           lambda_mtbf = 12 , 
                                                            lambda_mttr = 5)
machine_breakdowns

[{0: [{'TIME': 2.1177234649658203, 'DURATION': 13.687506675720215},
   {'TIME': 30.894084930419922, 'DURATION': 1.7353652715682983},
   {'TIME': 56.5755695104599, 'DURATION': 12.62062931060791}],
  1: [{'TIME': 20.940404891967773, 'DURATION': 1.911413550376892},
   {'TIME': 29.47150456905365, 'DURATION': 1.2553738355636597},
   {'TIME': 58.70567047595978, 'DURATION': 3.389516830444336}],
  2: [{'TIME': 8.795876502990723, 'DURATION': 0.09403666108846664},
   {'TIME': 37.67300757020712, 'DURATION': 1.5067274570465088},
   {'TIME': 50.73074667155743, 'DURATION': 0.8234021067619324}],
  3: [{'TIME': 4.745704174041748, 'DURATION': 3.364922046661377},
   {'TIME': 28.8924503326416, 'DURATION': 0.8307462930679321},
   {'TIME': 44.118542313575745, 'DURATION': 4.073455333709717},
   {'TIME': 92.94010615348816, 'DURATION': 0.33730676770210266}],
  4: [{'TIME': 2.0182857513427734, 'DURATION': 4.082698822021484},
   {'TIME': 32.093326568603516, 'DURATION': 2.2633883953094482},
   {'TIME': 48.919009

- Breakdown of the machine 4 in batch 0

In [20]:
machine_breakdowns[0][4]

[{'TIME': 2.0182857513427734, 'DURATION': 4.082698822021484},
 {'TIME': 32.093326568603516, 'DURATION': 2.2633883953094482},
 {'TIME': 48.91900992393494, 'DURATION': 1.6398956775665283},
 {'TIME': 92.2194093465805, 'DURATION': 0.44248250126838684}]

- Extracting Breakdown occurence time and breakdown duration

In [21]:
# breakdowns of the machine 5 in batch 3
b5 = td["machine_breakdowns"][3][5]
print(f"BREAKDOWNS OF MACHINE 5 IN BATCH 3{b5}")

print("--------------------------------------------")

# first breakdown occurence time of machine 5 in batch 3
first_b5 = td["machine_breakdowns"][3][5][0]["TIME"]
print(f"BREAKDOWN OCCURENCE : {first_b5}")

print("--------------------------------------------")

# first breakdown duration of machine 5 in batch 3
first_b5_duration = td["machine_breakdowns"][3][5][0]["DURATION"]
print(f"BREAKDOWN DURATION : {first_b5_duration}")

BREAKDOWNS OF MACHINE 5 IN BATCH 3[{'TIME': 32.70050048828125, 'DURATION': 2.011552572250366}, {'TIME': 46.81283640861511, 'DURATION': 4.536108016967773}, {'TIME': 113.29264879226685, 'DURATION': 0.011085120029747486}]
--------------------------------------------
BREAKDOWN OCCURENCE : 32.70050048828125
--------------------------------------------
BREAKDOWN DURATION : 2.011552572250366


In [22]:
type(machine_breakdowns)
len(machine_breakdowns)

4

### td["job_arrival_times"]

In [23]:
td["job_arrival_times"]

tensor([[  3.8915,  30.6388,  40.9094,  53.8382,  77.3067, 113.0761],
        [ 40.7505,  41.2100, 102.8515, 105.7987, 106.1392, 141.7041],
        [ 53.4563,  78.0810,  83.6696,  84.9191,  93.6855,  99.1691],
        [ 35.2858,  95.5298, 119.5022, 150.5760, 229.0147, 233.7219],
        [ 20.7289,  54.7562, 177.7038, 207.4180, 223.8273, 229.0612],
        [ 23.4265,  30.5009,  42.4133,  46.6411,  75.6858,  76.3683]])

- Each entry is a arrival time of the job at the index
    - meaning [batch_no][arr_time_job1 , arr_time_job2,  ........  ]
- In this method, we assumed that jobs are processed sequentially, one after another, starting with Job 0, followed by Job 1, then Job 2, and so on, as outlined in the paper.


- Arrival Time of the Job 3 in batch 2

In [24]:
td["job_arrival_times"][2][3]

tensor(84.9191)

#### documentation of `_generate_random_job_arrivals( number_of_jobs, E_new):`

In [25]:
num_jobs = 15
E_new = 12
a= djssp_generator._generate_random_job_arrivals(bs =[3,] ,number_of_jobs = num_jobs , E_new = E_new)
a

tensor([[  7.2422,  13.2761,  36.0765,  50.5037,  59.2018,  73.3834,  83.6091,
          90.3859, 120.2968, 123.0010, 141.3152, 142.7501, 165.3776, 196.9968,
         214.0367],
        [ 10.4858,  24.5059,  25.0573,  27.3160,  35.3940,  36.8057,  42.5863,
          43.0033,  73.9759,  76.2267,  88.3991, 103.7436, 131.1781, 160.1398,
         160.4701],
        [  8.3899,   8.9146,  14.3046,  17.8727,  18.6272,  42.7945,  64.1988,
          89.5424, 120.0149, 127.6458, 149.5568, 170.0984, 170.9025, 188.6912,
         190.6532]])