In [1]:
import torch

from rl4co.envs.scheduling.djssp.env import DJSSPEnv

generator_params = {"num_jobs":5 ,
    "num_machines": 6 ,
    "min_processing_time":1 ,
    "max_processing_time": 200 ,
    "mtbf" : 17 ,
    "mttr" : 4}
env = DJSSPEnv(generator_params=generator_params)

C:\Users\soner\anaconda3\envs\env_rl4co\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
td  = env.reset(batch_size=[1])

JOB WITH ID 2 not arrived yet
JOB WITH ID 3 not arrived yet
JOB WITH ID 4 not arrived yet


In [3]:
td

TensorDict(
    fields={
        action_mask: Tensor(shape=torch.Size([1, 6]), device=cpu, dtype=torch.bool, is_shared=False),
        actual_proc_times: Tensor(shape=torch.Size([1, 6, 30]), device=cpu, dtype=torch.float32, is_shared=False),
        adjacency: Tensor(shape=torch.Size([1, 30, 30]), device=cpu, dtype=torch.float32, is_shared=False),
        busy_until: Tensor(shape=torch.Size([1, 6]), device=cpu, dtype=torch.float32, is_shared=False),
        done: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        end_op_per_job: Tensor(shape=torch.Size([1, 5]), device=cpu, dtype=torch.int64, is_shared=False),
        finish_times: Tensor(shape=torch.Size([1, 30]), device=cpu, dtype=torch.float32, is_shared=False),
        is_ready: Tensor(shape=torch.Size([1, 30]), device=cpu, dtype=torch.bool, is_shared=False),
        job_arrival_times: Tensor(shape=torch.Size([1, 5]), device=cpu, dtype=torch.float32, is_shared=False),
        job_done: Tensor(sh

In [4]:
td["proc_times"][0]

tensor([[  0.,   0.,   0.,   0.,   0., 145.,   0.,   0.,   0., 130.,   0.,   0.,
           0.,   0.,   0.,   0.,  26.,   0.,   0.,   0., 150.,   0.,   0.,   0.,
         136.,   0.,   0.,   0.,   0.,   0.],
        [ 11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  37.,
           0.,   0.,   0.,   0.,   0., 126.,   0.,  26.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,  37.,   0.,   0.],
        [  0.,   0.,   0.,   0., 120.,   0.,   0.,   0.,  62.,   0.,   0.,   0.,
           0.,   0.,  40.,   0.,   0.,   0., 199.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,  76.,   0.,   0.,   0.],
        [  0.,   0.,   0., 126.,   0.,   0.,   0.,   0.,   0.,   0., 117.,   0.,
           0.,   0.,   0.,  31.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  67.,
           0.,   0.,   0.,   0., 168.,   0.],
        [  0.,   0., 176.,   0.,   0.,   0., 170.,   0.,   0.,   0.,   0.,   0.,
         135.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 194.,   0.,
      

In [5]:
env.num_mas

6

In [6]:
td["ma_assignment"][0]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0.]])

In [7]:
td["actual_proc_times"][0]

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000, 170.0129,   0.0000,
           0.0000,   0.0000, 127.1407,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,  25.3751,   0.0000,   0.0000,   0.0000, 155.8332,
           0.0000,   0.0000,   0.0000, 157.3247,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000],
        [ 10.8153,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,  24.2006,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000, 114.4445,   0.0000,  30.0945,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  33.6600,
           0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000, 113.8439,   0.0000,   0.0000,
           0.0000,  58.6793,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
          44.2891,   0.0000,   0.0000,   0.0000, 206.5757,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  69.3452,   

In [8]:
env.num_jobs

5

In [9]:
get_job_ma_avail = env._get_job_machine_availability(td)
get_job_ma_avail

JOB WITH ID 2 not arrived yet
JOB WITH ID 3 not arrived yet
JOB WITH ID 4 not arrived yet


tensor([[[ True, False,  True,  True,  True,  True],
         [ True,  True,  True,  True, False,  True],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False]]])

In [10]:
get_job_ma_avail.shape #5 jobs 6 machines

torch.Size([1, 5, 6])

In [11]:
job=0
get_job_ma_avail[0][job]

tensor([ True, False,  True,  True,  True,  True])

In [12]:
job=0
get_job_ma_avail[0][job].fill_(False)

tensor([False, False, False, False, False, False])

In [13]:
td["job_arrival_times"]

tensor([[13.7706, 36.8782, 63.9507, 72.1633, 73.9766]])

In [14]:
td["job_arrival_times"].squeeze(0).shape

torch.Size([5])

In [15]:
time = 38
boo = td["job_arrival_times"].squeeze(0).ge(time)
boo

tensor([False, False,  True,  True,  True])

In [16]:
for i in range(env.num_jobs):
    if(not boo[i]):
        get_job_ma_avail[0][i].fill_(False)
get_job_ma_avail

tensor([[[False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False]]])

In [17]:
job=1
get_job_ma_avail[0][job].fill_(False)

tensor([False, False, False, False, False, False])

In [18]:
get_job_ma_avail.squeeze(0)

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [19]:
env._get_job_machine_availability(td)

JOB WITH ID 2 not arrived yet
JOB WITH ID 3 not arrived yet
JOB WITH ID 4 not arrived yet


tensor([[[ True, False,  True,  True,  True,  True],
         [ True,  True,  True,  True, False,  True],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False]]])

In [20]:
env._get_job_machine_availability(td)

JOB WITH ID 2 not arrived yet
JOB WITH ID 3 not arrived yet
JOB WITH ID 4 not arrived yet


tensor([[[ True, False,  True,  True,  True,  True],
         [ True,  True,  True,  True, False,  True],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False],
         [False, False, False, False, False, False]]])

In [21]:
td["time"]

tensor([46.])

In [22]:
torch.Tensor([12.])

tensor([12.])

# JSSP

In [23]:
from rl4co.envs.scheduling.jssp.env import JSSPEnv
jssp_gen_params = {"num_jobs":5 ,
    "num_machines": 6 ,
    "min_processing_time":1 ,
    "max_processing_time": 200 }
jssp = JSSPEnv(generator_params=jssp_gen_params)
jssp_td = jssp.reset(batch_size=[2])

In [24]:
jssp_td["proc_times"][0]

tensor([[  0.,   0.,   0.,   0.,   0., 162.,   0.,   0., 124.,   0.,   0.,   0.,
           0.,   0., 188.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  75.,
          31.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,  56.,   0.,   0.,   0.,   0.,   0.,   0., 183.,   0.,
           0., 100.,   0.,   0.,   0.,   0.,   0.,   0., 156.,   0.,   0.,   0.,
           0.,   0.,   0.,  98.,   0.,   0.],
        [  0., 138.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  93.,
           0.,   0.,   0.,  55.,   0.,   0.,  90.,   0.,   0.,   0.,   0.,   0.,
           0., 139.,   0.,   0.,   0.,   0.],
        [ 64.,   0.,   0.,   0.,   0.,   0.,   0., 164.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   7.,   0., 119.,   0.,   0.,   0.,   0.,
           0.,   0.,  81.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   6.,   0.,   0.,   0.,   0., 158.,   0.,   0.,
           6.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  78.,   0.,   0.,
      

In [25]:
action_mask_table =jssp.get_action_mask(jssp_td)
action_mask_table

tensor([[False,  True,  True,  True,  True,  True],
        [False,  True,  True,  True,  True,  True]])

In [26]:
from rl4co.models.nn.graph.hgnn import HetGNNEncoder

encoder = HetGNNEncoder(embed_dim=64, num_layers=2)
(ma_emb, op_emb), init = encoder(jssp_td)
print(ma_emb.shape)
print(op_emb.shape)

torch.Size([2, 30, 64])
torch.Size([2, 6, 64])


In [27]:
jssp_td["next_op"]

tensor([[ 0,  6, 12, 18, 24],
        [ 0,  6, 12, 18, 24]])

In [28]:
from rl4co.models.zoo.l2d.decoder import L2DDecoder

decoder = L2DDecoder(env_name="jssp", embed_dim=128)
logits, mask = decoder(jssp_td, (ma_emb, op_emb), num_starts=0)
# (1 + num_jobs * num_machines)
print(logits.shape)
logits

torch.Size([2, 6])


tensor([[ 0.0428,  0.1844,  0.1832,  0.0908,  0.0502, -0.0605],
        [ 0.0428,  0.3434,  0.2670,  0.2131,  0.2765,  0.1645]],
       grad_fn=<SqueezeBackward1>)

In [29]:
def make_step(td):
    logits, mask = decoder(td, (ma_emb, op_emb), num_starts=0)
    action = logits.masked_fill(~mask, -torch.inf).argmax(1)
    td["action"] = action
    td = env.step(td)["next"]
    return td

In [30]:
action = logits.masked_fill(~mask, -torch.inf).argmax(1)
action

tensor([1, 1])

In [31]:
jssp_td["action"] = action
action[0]

tensor(1)

In [32]:
action[1]

tensor(1)

In [33]:
stepten_sonra = jssp.step(jssp_td)["next"]
stepten_sonra["proc_times"][1]
# J1'in ilk operation'ini yapmis -> yani action == 1 demek -> ilk operasyonu yap demek -> yani su mantik J0[yok] J1[0-5] J2[6-11] J3[12-17] J4[18-23] J5[24-29]
# get_action_mask'in bir tane fazla x_achse'sinin olma sebebi ve bunun hep false olma sebebi-> J0'in olmamasi ya da en azindan secilememsi aksiyon olarak
# aksiyon olarka secilebilecek joblarin indexi hep 1'den basliyor

tensor([[  0.,   0.,  81.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 198.,   0.,
           0.,   0.,   0.,  95.,   0.,   0.,   0.,   0.,   0.,  34.,   0.,   0.,
           0.,   0.,  60.,   0.,   0.,   0.],
        [  0.,   0.,   0., 198.,   0.,   0.,   0.,   0.,   0., 134.,   0.,   0.,
           0.,   0.,   0.,   0.,   0., 141.,   0.,   0.,   0.,   0.,   0., 156.,
           0.,   0.,   0.,   0.,   9.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0., 127.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,  38.,   0.,   3.,   0.,   0.,   0.,   0.,   0.,
          89.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,  10.,   0.,   0.,   0., 108.,   0.,   0.,   0.,
           0.,   0.,  77.,   0.,   0.,   0.,   0.,   0.,  80.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,  34.],
        [  0., 134.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 147.,
           0., 115.,   0.,   0.,   0.,   0.,   0.,  20.,   0.,   0.,   0.,   0.,
      

In [34]:
stepten_sonra["proc_times"][0]
# J2'nin ilk operasyonunu yapmasi gerekiyor -> cünkü secilen action 2 == job2 --> action_mask table'da neden hala ilk column full yanlis anlamiyorum
# yani yapmis olmasi gerekn operation 12

tensor([[  0.,   0.,   0.,   0.,   0., 162.,   0.,   0., 124.,   0.,   0.,   0.,
           0.,   0., 188.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  75.,
          31.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,  56.,   0.,   0.,   0.,   0.,   0.,   0., 183.,   0.,
           0., 100.,   0.,   0.,   0.,   0.,   0.,   0., 156.,   0.,   0.,   0.,
           0.,   0.,   0.,  98.,   0.,   0.],
        [  0., 138.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  93.,
           0.,   0.,   0.,  55.,   0.,   0.,  90.,   0.,   0.,   0.,   0.,   0.,
           0., 139.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0., 164.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   7.,   0., 119.,   0.,   0.,   0.,   0.,
           0.,   0.,  81.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   6.,   0.,   0.,   0.,   0., 158.,   0.,   0.,
           6.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  78.,   0.,   0.,
      